### ISSUE TITLE
支持新的文件后缀？

### ISSUE THREAD

**Issue by idoall** [graphman65/vscode-tengo#1]
使用tengo，我用了其他的扩展名，比如.mshk，如何让这个插件支持新的文件后缀？

**Comment by idoall** [comment]
VS版本1.45.0

**Comment by idoall** [comment]
在~/.vscode找到了配置文件，加了其他文件的支持，但在vs.net工具中看不到设置的地方

**Comment by lissein** [comment]
Hi,
You can use the "files.associations" setting in vscode.
In your case:
```json
"files.associations": {
    "*.mshk": "tengo"
}
```
